-- 코드를 입력하세요
/*
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
from REST_INFO
where (Food_TYPE, FAVORITES) in (
    SELECT FOOD_TYPE, max(FAVORITES)
    FROM REST_INFO
    group by FOOD_TYPE
)
order by FOOD_TYPE desc
*/


SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT *, 
           RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) as rnk
    FROM REST_INFO
) AS ranked_table
WHERE rnk = 1
ORDER BY FOOD_TYPE DESC;
