


SELECT a.ID, c.FISH_NAME, b.LENGTH
FROM FISH_INFO as a
join (SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
     ) as b
    on a.FISH_TYPE = b.FISH_TYPE and a.LENGTH = b.LENGTH
join FISH_NAME_INFO as c
    on b.FISH_TYPE = c.FISH_TYPE
order by a.ID