-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT a.ID, b.FISH_NAME, a.LENGTH, MAX(a.LENGTH) OVER(PARTITION BY b.FISH_NAME) as MAX_LENGTH
    FROM FISH_INFO a join FISH_NAME_INFO b on a.FISH_TYPE = b.FISH_TYPE
) sub
WHERE LENGTH = MAX_LENGTH
ORDER BY ID ASC

